### ISSUE TITLE
District Numbers don't match District Shapes

### ISSUE THREAD

**Issue by hunterowens** [datala/311-analysis#9]
On the map, the district numbers don't match the district shapes

**Comment by hunterowens** [comment]
Any ideas @robertmitchellv

**Comment by robertmitchellv** [comment]
#10 will fix this, I assumed that using `arrange` with `districts@data` when loading the shapefile would extend to the polygons, but it just messed with the labels instead.  Once I removed those 2/3 lines it was fine!
